//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLFS.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CinemaLFS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty field.
        /// </summary>
        internal static string Campo_vacio {
            get {
                return ResourceManager.GetString("Campo vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount of tiquets.
        /// </summary>
        internal static string Cantidad_de_boletas {
            get {
                return ResourceManager.GetString("Cantidad de boletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cinema.
        /// </summary>
        internal static string Cine {
            get {
                return ResourceManager.GetString("Cine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premier.
        /// </summary>
        internal static string Estreno {
            get {
                return ResourceManager.GetString("Estreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Function.
        /// </summary>
        internal static string Funcion {
            get {
                return ResourceManager.GetString("Funcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login .
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the user.
        /// </summary>
        internal static string Ingrese_el_usuario {
            get {
                return ResourceManager.GetString("Ingrese el usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the amount of tiquets.
        /// </summary>
        internal static string Ingrese_la_cantidad_de_boletas {
            get {
                return ResourceManager.GetString("Ingrese la cantidad de boletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the password.
        /// </summary>
        internal static string Ingrese_la_password {
            get {
                return ResourceManager.GetString("Ingrese la password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try again.
        /// </summary>
        internal static string Intentalo_de_nuevo {
            get {
                return ResourceManager.GetString("Intentalo de nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The reservation was made correctly.
        /// </summary>
        internal static string La_reserva_se_realizo_correctamente {
            get {
                return ResourceManager.GetString("La reserva se realizo correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are sorry.
        /// </summary>
        internal static string Lo_sentimos {
            get {
                return ResourceManager.GetString("Lo sentimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movie.
        /// </summary>
        internal static string Pelicula {
            get {
                return ResourceManager.GetString("Pelicula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room.
        /// </summary>
        internal static string Sala {
            get {
                return ResourceManager.GetString("Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem.
        /// </summary>
        internal static string Se_presento_un_problema {
            get {
                return ResourceManager.GetString("Se presento un problema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiquets.
        /// </summary>
        internal static string Tiquetes {
            get {
                return ResourceManager.GetString("Tiquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tittle.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total to pay.
        /// </summary>
        internal static string Total_a_pagar {
            get {
                return ResourceManager.GetString("Total a pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation.
        /// </summary>
        internal static string Validacion {
            get {
                return ResourceManager.GetString("Validacion", resourceCulture);
            }
        }
    }
}
